name = "ITP_course"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ITPCourse"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
warn.sorry = false    # Don't warn for sorry

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "ITPCourse"
